#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
  :github => 'opscode-cookbooks/apt'
cookbook 'git',
  :github => 'opscode-cookbooks/git'
cookbook 'mysql',
  :github => 'opscode-cookbooks/mysql'
cookbook 'database',
  :github => 'opscode-cookbooks/database'
cookbook 'apache2',
  :github => 'opscode-cookbooks/apache2'
cookbook 'build-essential'